server:
  port: 9090

# 数据库配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 690325
    url: jdbc:mysql://localhost:3306/supermarketmanagementsystem?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #---- ^ redis 配置 ----#
  cache:
    type: redis # 缓存类型
  redis:
    host: localhost # Redis数据库主机
    port: 6379 # Redis数据库端口
    password: 690325 # Redis数据库密码
    database: 15 # Redis数据库索引
    timeout: 5000 # Redis数据库连接超时时间，尽量不要零
    jedis:
      pool:
        max-active: 8 # Redis数据库连接池最大连接数
        max-idle: 8 # Redis数据库连接池最大空闲连接数
        min-idle: 0 # Redis数据库连接池最小空闲连接数
        max-wait: -1 # Redis数据库连接池最大阻塞等待时间
  #---- / redis 配置 ----#

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
